// Code generated by mapgen filter; DO NOT EDIT.

package user

import (
	"github.com/kitti12911/lib-util/v3/apperror"

	fieldmap "grpc-sandbox/gen/database"

	orm "github.com/kitti12911/lib-orm/v4"
	"github.com/uptrace/bun"
)

var userCustomFilters = map[string]orm.FilterExpr{}

func applyFilter(query *bun.SelectQuery, filter orm.Filter) error {
	if err := orm.ApplyFilter(query, filter, fieldmap.UserColumns, userCustomFilters); err != nil {
		return apperror.InvalidInput("invalid filter", err)
	}
	return nil
}

func applyOrderBy(query *bun.SelectQuery, orderBy []orm.OrderBy) error {
	if err := orm.ApplyOrderBy(query, orderBy, fieldmap.UserColumns); err != nil {
		return apperror.InvalidInput("invalid order by", err)
	}
	return nil
}
