// Code generated by mapgen map; DO NOT EDIT.

package user

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	userv1 "grpc-sandbox/gen/grpc/user/v1"
	database "grpc-sandbox/internal/database"
)

// toProtoUser maps a User to its proto representation.
func toProtoUser(src *database.User) *userv1.User {
	if src == nil {
		return nil
	}
	dst := &userv1.User{
		CreatedAt:   timestamppb.New(src.CreatedAt),
		DisplayName: src.DisplayName,
		Email:       src.Email,
		Id:          src.ID,
		Profile:     toProtoUserProfile(src.Profile),
		Status:      toProtoUserStatus(src.Status),
		UpdatedAt:   timestamppb.New(src.UpdatedAt),
		Username:    src.Username,
	}
	return dst
}

// toProtoUserProfile maps a UserProfile to its proto representation.
func toProtoUserProfile(src *database.UserProfile) *userv1.UserProfile {
	if src == nil {
		return nil
	}
	dst := &userv1.UserProfile{
		Address:     toProtoUserAddress(src.Address),
		FirstName:   src.FirstName,
		LastName:    src.LastName,
		PhoneNumber: src.PhoneNumber,
	}
	return dst
}

// toProtoUserAddress maps a UserAddress to its proto representation.
func toProtoUserAddress(src *database.UserAddress) *userv1.UserAddress {
	if src == nil {
		return nil
	}
	dst := &userv1.UserAddress{
		City:        src.City,
		CountryCode: src.CountryCode,
		Line1:       src.Line1,
		Line2:       src.Line2,
		PostalCode:  src.PostalCode,
		State:       src.State,
	}
	return dst
}

// createParamsFromProto maps userv1.User back to CreateParams.
func createParamsFromProto(in *userv1.User) CreateParams {
	if in == nil {
		return CreateParams{}
	}
	dst := CreateParams{
		DisplayName: in.DisplayName,
		Email:       in.Email,
		Profile:     createProfileParamsFromProto(in.Profile),
		Status:      userStatusFromProto(in.Status),
		Username:    in.Username,
	}
	return dst
}

// createProfileParamsFromProto maps userv1.UserProfile back to CreateProfileParams.
func createProfileParamsFromProto(in *userv1.UserProfile) *CreateProfileParams {
	if in == nil {
		return nil
	}
	dst := &CreateProfileParams{
		Address:     createAddressParamsFromProto(in.Address),
		FirstName:   in.FirstName,
		LastName:    in.LastName,
		PhoneNumber: in.PhoneNumber,
	}
	return dst
}

// createAddressParamsFromProto maps userv1.UserAddress back to CreateAddressParams.
func createAddressParamsFromProto(in *userv1.UserAddress) *CreateAddressParams {
	if in == nil {
		return nil
	}
	dst := &CreateAddressParams{
		City:        in.City,
		CountryCode: in.CountryCode,
		Line1:       in.Line1,
		Line2:       in.Line2,
		PostalCode:  in.PostalCode,
		State:       in.State,
	}
	return dst
}

// toProtoUserStatus maps a string to the userv1.UserStatus enum.
func toProtoUserStatus(value string) userv1.UserStatus {
	switch value {
	case "active":
		return userv1.UserStatus_USER_STATUS_ACTIVE
	case "disabled":
		return userv1.UserStatus_USER_STATUS_DISABLED
	case "pending":
		return userv1.UserStatus_USER_STATUS_PENDING
	default:
		return userv1.UserStatus_USER_STATUS_UNSPECIFIED
	}
}

// userStatusFromProto maps the userv1.UserStatus enum to a string.
func userStatusFromProto(value userv1.UserStatus) string {
	switch value {
	case userv1.UserStatus_USER_STATUS_ACTIVE:
		return "active"
	case userv1.UserStatus_USER_STATUS_DISABLED:
		return "disabled"
	case userv1.UserStatus_USER_STATUS_PENDING:
		return "pending"
	default:
		return ""
	}
}
