// Code generated by patchfieldgen; DO NOT EDIT.

package user

import fieldmap "grpc-sandbox/gen/database"

func patchFields(params PatchParams) patchData {
	data := patchData{
		userFields:    make(map[string]any),
		profileFields: make(map[string]any),
		addressFields: make(map[string]any),
	}

	if params.User.Profile != nil {
		data.profile = *params.User.Profile
		if params.User.Profile.Address != nil {
			data.address = *params.User.Profile.Address
		}
	}

	for _, path := range params.Fields {
		switch path {
		case "display_name":
			if fieldmap.IsUserRootField("display_name") {
				data.userFields["display_name"] = params.User.DisplayName
			}
		case "email":
			if fieldmap.IsUserRootField("email") {
				data.userFields["email"] = params.User.Email
			}
		case "profile.address.city":
			if params.User.Profile == nil {
				data.addressFields["city"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["city"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("city") {
				data.addressFields["city"] = params.User.Profile.Address.City
			}
		case "profile.address.country_code":
			if params.User.Profile == nil {
				data.addressFields["country_code"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["country_code"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("country_code") {
				data.addressFields["country_code"] = params.User.Profile.Address.CountryCode
			}
		case "profile.address.line1":
			if params.User.Profile == nil {
				data.addressFields["line1"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["line1"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("line1") {
				data.addressFields["line1"] = params.User.Profile.Address.Line1
			}
		case "profile.address.line2":
			if params.User.Profile == nil {
				data.addressFields["line2"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["line2"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("line2") {
				data.addressFields["line2"] = params.User.Profile.Address.Line2
			}
		case "profile.address.postal_code":
			if params.User.Profile == nil {
				data.addressFields["postal_code"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["postal_code"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("postal_code") {
				data.addressFields["postal_code"] = params.User.Profile.Address.PostalCode
			}
		case "profile.address.state":
			if params.User.Profile == nil {
				data.addressFields["state"] = nil
				continue
			}
			if params.User.Profile.Address == nil {
				data.addressFields["state"] = nil
				continue
			}
			if fieldmap.IsUserAddressField("state") {
				data.addressFields["state"] = params.User.Profile.Address.State
			}
		case "profile.first_name":
			if params.User.Profile == nil {
				data.profileFields["first_name"] = nil
				continue
			}
			if fieldmap.IsUserProfileField("first_name") {
				data.profileFields["first_name"] = params.User.Profile.FirstName
			}
		case "profile.last_name":
			if params.User.Profile == nil {
				data.profileFields["last_name"] = nil
				continue
			}
			if fieldmap.IsUserProfileField("last_name") {
				data.profileFields["last_name"] = params.User.Profile.LastName
			}
		case "profile.phone_number":
			if params.User.Profile == nil {
				data.profileFields["phone_number"] = nil
				continue
			}
			if fieldmap.IsUserProfileField("phone_number") {
				data.profileFields["phone_number"] = params.User.Profile.PhoneNumber
			}
		case "status":
			if fieldmap.IsUserRootField("status") {
				data.userFields["status"] = params.User.Status
			}
		case "username":
			if fieldmap.IsUserRootField("username") {
				data.userFields["username"] = params.User.Username
			}
		}
	}

	return data
}
