// Code generated by patchfieldgen; DO NOT EDIT.

package user

func patchFields(params PatchParams) patchData {
	data := patchData{
		addressFields: make(map[string]any),
		profileFields: make(map[string]any),
		userFields:    make(map[string]any),
	}

	if params.User.Profile != nil {
		data.profile = *params.User.Profile
	}

	if params.User.Profile != nil && params.User.Profile.Address != nil {
		data.address = *params.User.Profile.Address
	}

	for _, path := range params.Fields {
		switch path {
		case "display_name":
			data.userFields["display_name"] = params.User.DisplayName
		case "email":
			data.userFields["email"] = params.User.Email
		case "profile.address.city":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["city"] = nil
				continue
			}
			data.addressFields["city"] = params.User.Profile.Address.City
		case "profile.address.country_code":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["country_code"] = nil
				continue
			}
			data.addressFields["country_code"] = params.User.Profile.Address.CountryCode
		case "profile.address.line1":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["line1"] = nil
				continue
			}
			data.addressFields["line1"] = params.User.Profile.Address.Line1
		case "profile.address.line2":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["line2"] = nil
				continue
			}
			data.addressFields["line2"] = params.User.Profile.Address.Line2
		case "profile.address.postal_code":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["postal_code"] = nil
				continue
			}
			data.addressFields["postal_code"] = params.User.Profile.Address.PostalCode
		case "profile.address.state":
			if params.User.Profile == nil || params.User.Profile.Address == nil {
				data.addressFields["state"] = nil
				continue
			}
			data.addressFields["state"] = params.User.Profile.Address.State
		case "profile.first_name":
			if params.User.Profile == nil {
				data.profileFields["first_name"] = nil
				continue
			}
			data.profileFields["first_name"] = params.User.Profile.FirstName
		case "profile.last_name":
			if params.User.Profile == nil {
				data.profileFields["last_name"] = nil
				continue
			}
			data.profileFields["last_name"] = params.User.Profile.LastName
		case "profile.phone_number":
			if params.User.Profile == nil {
				data.profileFields["phone_number"] = nil
				continue
			}
			data.profileFields["phone_number"] = params.User.Profile.PhoneNumber
		case "status":
			data.userFields["status"] = params.User.Status
		case "username":
			data.userFields["username"] = params.User.Username
		}
	}

	return data
}
