package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

type field struct {
	path     string
	key      string
	selector string
	guards   []string
	bucket   string
}

type model struct {
	name   string
	fields []modelField
}

type modelField struct {
	name      string
	tag       string
	typeName  string
	isPointer bool
}

func main() {
	filePath := flag.String("file", "", "Go source file containing patch params")
	rootName := flag.String("root", "", "root struct type name")
	outPath := flag.String("out", "", "generated Go output path")
	packageName := flag.String("package", "", "generated Go package name")
	functionName := flag.String("function", "patchFields", "generated function name")
	fieldMapImport := flag.String("fieldmap-import", "", "field map package import path")
	flag.Parse()

	if *filePath == "" || *rootName == "" || *outPath == "" || *packageName == "" || *fieldMapImport == "" {
		panic("file, root, out, package, and fieldmap-import are required")
	}

	models, err := parseModels(*filePath)
	if err != nil {
		panic(err)
	}

	fields := collectFields(models, *rootName, "", "params.User", nil)
	sort.Slice(fields, func(i, j int) bool {
		return fields[i].path < fields[j].path
	})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by patchfieldgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *packageName)
	fmt.Fprintf(&buf, "import fieldmap %q\n\n", *fieldMapImport)
	fmt.Fprintf(&buf, "func %s(params PatchParams) patchData {\n", *functionName)
	buf.WriteString("\tdata := patchData{\n")
	buf.WriteString("\t\tuserFields:    make(map[string]any),\n")
	buf.WriteString("\t\tprofileFields: make(map[string]any),\n")
	buf.WriteString("\t\taddressFields: make(map[string]any),\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\tif params.User.Profile != nil {\n")
	buf.WriteString("\t\tdata.profile = *params.User.Profile\n")
	buf.WriteString("\t\tif params.User.Profile.Address != nil {\n")
	buf.WriteString("\t\t\tdata.address = *params.User.Profile.Address\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\tfor _, path := range params.Fields {\n")
	buf.WriteString("\t\tswitch path {\n")
	for _, field := range fields {
		fmt.Fprintf(&buf, "\t\tcase %q:\n", field.path)
		for _, guard := range field.guards {
			fmt.Fprintf(&buf, "\t\t\tif %s == nil {\n", guard)
			fmt.Fprintf(&buf, "\t\t\t\tdata.%s[%q] = nil\n", field.bucket, field.key)
			buf.WriteString("\t\t\t\tcontinue\n")
			buf.WriteString("\t\t\t}\n")
		}
		fmt.Fprintf(&buf, "\t\t\tif %s(%q) {\n", validatorFor(field.bucket), field.key)
		fmt.Fprintf(&buf, "\t\t\t\tdata.%s[%q] = %s\n", field.bucket, field.key, field.selector)
		buf.WriteString("\t\t\t}\n")
	}
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\treturn data\n")
	buf.WriteString("}\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*outPath, out, 0o644); err != nil {
		panic(err)
	}
}

func parseModels(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec := spec.(*ast.TypeSpec)
			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			models[typeSpec.Name.Name] = parseModel(typeSpec.Name.Name, strct)
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) model {
	m := model{name: name}
	for _, field := range strct.Fields.List {
		if len(field.Names) == 0 {
			continue
		}

		tag := ""
		if field.Tag != nil {
			tag = reflect.StructTag(strings.Trim(field.Tag.Value, "`")).Get("field")
		}
		if tag == "" {
			continue
		}

		typeName, isPointer := typeName(field.Type)
		if typeName == "" {
			continue
		}

		m.fields = append(m.fields, modelField{
			name:      field.Names[0].Name,
			tag:       tag,
			typeName:  typeName,
			isPointer: isPointer,
		})
	}
	return m
}

func collectFields(models map[string]model, typeName string, prefix string, selector string, guards []string) []field {
	m, ok := models[typeName]
	if !ok {
		return nil
	}

	fields := make([]field, 0, len(m.fields))
	for _, modelField := range m.fields {
		path := modelField.tag
		if prefix != "" {
			path = prefix + "." + modelField.tag
		}

		nextSelector := selector + "." + modelField.name
		nextGuards := guards
		if modelField.isPointer {
			nextGuards = append(append([]string{}, guards...), nextSelector)
		}

		if _, ok := models[modelField.typeName]; ok {
			fields = append(fields, collectFields(models, modelField.typeName, path, nextSelector, nextGuards)...)
			continue
		}

		fields = append(fields, field{
			path:     path,
			key:      modelField.tag,
			selector: nextSelector,
			guards:   guards,
			bucket:   bucketFor(path),
		})
	}
	return fields
}

func typeName(expr ast.Expr) (string, bool) {
	switch expr := expr.(type) {
	case *ast.Ident:
		return expr.Name, false
	case *ast.StarExpr:
		name, _ := typeName(expr.X)
		return name, true
	default:
		return "", false
	}
}

func bucketFor(path string) string {
	switch {
	case strings.HasPrefix(path, "profile.address."):
		return "addressFields"
	case strings.HasPrefix(path, "profile."):
		return "profileFields"
	default:
		return "userFields"
	}
}

func validatorFor(bucket string) string {
	switch bucket {
	case "addressFields":
		return "fieldmap.IsUserAddressField"
	case "profileFields":
		return "fieldmap.IsUserProfileField"
	default:
		return "fieldmap.IsUserRootField"
	}
}
