package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"
)

var excludedColumns = map[string]bool{
	"id":              true,
	"user_id":         true,
	"user_profile_id": true,
	"created_at":      true,
	"updated_at":      true,
}

type model struct {
	name      string
	table     string
	columns   map[string]string
	relations []relation
}

type relation struct {
	name  string
	model string
	child bool
}

func main() {
	modelPath := flag.String("model", "internal/database/model.go", "Go source file containing Bun models")
	outPath := flag.String("out", "gen/database/fieldmap_generated.go", "generated Go output path")
	packageName := flag.String("package", "database", "generated Go package name")
	flag.Parse()

	models, err := parseModels(*modelPath)
	if err != nil {
		panic(err)
	}

	root, ok := models["User"]
	if !ok {
		panic("User model not found")
	}

	maps := map[string]map[string]string{}
	visit(models, root, rootName, maps, map[string]bool{})

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", *packageName)
	buf.WriteString("const UserRootNestedName = \"root\"\n\n")
	writeMap(&buf, "UserRootFields", maps[rootName])
	writeMap(&buf, "UserProfileFields", maps["profile"])
	writeMap(&buf, "UserAddressFields", maps["profile.address"])

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.MkdirAll(filepath.Dir(*outPath), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*outPath, out, 0o644); err != nil {
		panic(err)
	}
}

const rootName = "root"

func visit(models map[string]model, m model, nestedName string, maps map[string]map[string]string, seen map[string]bool) {
	if seen[m.name] {
		return
	}
	seen[m.name] = true

	maps[nestedName] = m.columns

	for _, rel := range m.relations {
		if !rel.child {
			continue
		}

		relModel, ok := models[rel.model]
		if !ok {
			continue
		}

		childName := snake(rel.name)
		if nestedName != rootName {
			childName = nestedName + "." + childName
		}
		visit(models, relModel, childName, maps, seen)
	}
}

func parseModels(path string) (map[string]model, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	models := make(map[string]model)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}

		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			strct, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			m, ok := parseModel(typeSpec.Name.Name, strct)
			if ok {
				models[m.name] = m
			}
		}
	}

	return models, nil
}

func parseModel(name string, strct *ast.StructType) (model, bool) {
	m := model{
		name:    name,
		columns: make(map[string]string),
	}

	for _, field := range strct.Fields.List {
		tag := structTag(field)
		bunTag := tag.Get("bun")
		if bunTag == "" {
			continue
		}

		if len(field.Names) == 0 && strings.Contains(bunTag, "table:") {
			m.table = tagOptionValue(bunTag, "table")
			continue
		}

		if len(field.Names) == 0 {
			continue
		}

		fieldName := field.Names[0].Name
		if strings.Contains(bunTag, "rel:") {
			m.relations = append(m.relations, relation{
				name:  fieldName,
				model: modelTypeName(field.Type),
				child: !strings.Contains(bunTag, "rel:belongs-to"),
			})
			continue
		}

		column := strings.Split(bunTag, ",")[0]
		if column == "" || excludedColumns[column] {
			continue
		}
		m.columns[snake(fieldName)] = column
	}

	sort.Slice(m.relations, func(i, j int) bool {
		return m.relations[i].name < m.relations[j].name
	})

	return m, m.table != ""
}

func structTag(field *ast.Field) reflect.StructTag {
	if field.Tag == nil {
		return ""
	}
	return reflect.StructTag(strings.Trim(field.Tag.Value, "`"))
}

func tagOptionValue(tag string, key string) string {
	for _, opt := range strings.Split(tag, ",") {
		if value, ok := strings.CutPrefix(opt, key+":"); ok {
			return value
		}
	}
	return ""
}

func modelTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.StarExpr:
		return modelTypeName(t.X)
	case *ast.ArrayType:
		return modelTypeName(t.Elt)
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func writeMap(buf *bytes.Buffer, name string, fields map[string]string) {
	fmt.Fprintf(buf, "var %s = map[string]string{\n", name)
	keys := make([]string, 0, len(fields))
	for key := range fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", key, fields[key])
	}
	buf.WriteString("}\n\n")
}

func snake(name string) string {
	var out []rune
	for i, r := range name {
		if unicode.IsUpper(r) {
			if i > 0 {
				out = append(out, '_')
			}
			out = append(out, unicode.ToLower(r))
			continue
		}
		out = append(out, r)
	}
	return string(out)
}
